In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [236]:
d1 = pd.read_csv('football+players+data.csv',index_col=0)
d1.head()

ID               Name  Age Nationality  Overall  Potential  \
0  158023           L. Messi   31   Argentina       94         94   
1   20801  Cristiano Ronaldo   33    Portugal       94         94   
2  190871          Neymar Jr   26      Brazil       92         93   
3  193080             De Gea   27       Spain       91         93   
4  192985       K. De Bruyne   27     Belgium       91         92   

                  Club    Value   Wage  Special  ...   Body Type  Real Face  \
0         FC Barcelona  �110.5M  �565K     2202  ...       Messi        Yes   
1             Juventus     �77M  �405K     2228  ...  C. Ronaldo        Yes   
2  Paris Saint-Germain  �118.5M  �290K     2143  ...      Neymar        Yes   
3    Manchester United     �72M  �260K     1471  ...        Lean        Yes   
4      Manchester City    �102M  �355K     2281  ...      Normal        Yes   

   Position  Jersey Number     Joined Loaned From Contract Valid Until Height  \
0        RF           10.0  01-Jul-04         NaN                 2021    5'7   
1        ST            7.0  10-Jul-18         NaN                 2022    6'2   
2        LW           10.0  03-Aug-17         NaN                 2022    5'9   
3        GK            1.0  01-Jul-11         NaN                 2020    6'4   
4       RCM            7.0  30-Aug-15         NaN                 2023   5'11   

   Weight Release Clause  
0  159lbs        �226.5M  
1  183lbs        �127.1M  
2  150lbs        �228.1M  
3  168lbs        �138.6M  
4  154lbs        �196.4M  

[5 rows x 25 columns]

In [156]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18207 entries, 0 to 18206
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        18207 non-null  int64  
 1   Name                      18207 non-null  object 
 2   Age                       18207 non-null  int64  
 3   Nationality               18207 non-null  object 
 4   Overall                   18207 non-null  int64  
 5   Potential                 18207 non-null  int64  
 6   Club                      17966 non-null  object 
 7   Value                     18207 non-null  object 
 8   Wage                      18207 non-null  object 
 9   Special                   18207 non-null  int64  
 10  Preferred Foot            18159 non-null  object 
 11  International Reputation  18159 non-null  float64
 12  Weak Foot                 18159 non-null  float64
 13  Skill Moves               18159 non-null  float64
 14  Work R

In [235]:
d1['Name'].value_counts()

J. Rodr�guez      11
Paulinho           8
J. Williams        7
R. Williams        7
J. Hern�ndez       6
                  ..
H. Rivero          1
Choi Sung Keun     1
J. McLaughlin      1
J. Reeves          1
P. Stolarski       1
Name: Name, Length: 17189, dtype: int64

In [157]:
d1.isnull().sum()/len(d1)*100

ID                           0.000000
Name                         0.000000
Age                          0.000000
Nationality                  0.000000
Overall                      0.000000
Potential                    0.000000
Club                         1.323667
Value                        0.000000
Wage                         0.000000
Special                      0.000000
Preferred Foot               0.263635
International Reputation     0.263635
Weak Foot                    0.263635
Skill Moves                  0.263635
Work Rate                    0.263635
Body Type                    0.263635
Real Face                    0.263635
Position                     0.329544
Jersey Number                0.329544
Joined                       8.529686
Loaned From                 93.057615
Contract Valid Until         1.587302
Height                       0.263635
Weight                       0.263635
Release Clause               8.590103
dtype: float64

In [158]:
d1.drop('Loaned From',axis=1,inplace=True)

In [232]:
d1['Value'].unique()

array(['�110.5M', '�77M', '�118.5M', '�72M', '�102M', '�93M', '�67M',
       '�80M', '�51M', '�68M', '�76.5M', '�44M', '�60M', '�63M', '�89M',
       '�83.5M', '�78M', '�58M', '�53.5M', '�51.5M', '�38M', '�64.5M',
       '�27M', '�81M', '�69.5M', '�59.5M', '�62M', '�73.5M', '�59M',
       '�46M', '�43M', '�36M', '�57M', '�24M', '�30M', '�4M', '�64M',
       '�30.5M', '�62.5M', '�52M', '�45M', '�34M', '�46.5M', '�61M',
       '�41.5M', '�44.5M', '�56.5M', '�53M', '�50M', '�55M', '�36.5M',
       '�45.5M', '�43.5M', '�35M', '�39M', '�18M', '�21.5M', '�50.5M',
       '�54M', '�40.5M', '�37.5M', '�28.5M', '�37M', '�32M', '�26M',
       '�33M', '�38.5M', '�35.5M', '�9M', '�15.5M', '�22M', '�14M',
       '�42.5M', '�31.5M', '�42M', '�25M', '�29.5M', '�31M', '�24.5M',
       '�27.5M', '�29M', '�16.5M', '�23M', '�19M', '�4.2M', '�40M',
       '�41M', '�28M', '�22.5M', '�34.5M', '�32.5M', '�20M', '�26.5M',
       '�25.5M', '�21M', '�13M', '�17.5M', '�11.5M', '�8M', '�6M',
       '�19.5M', '�6.5

In [162]:
d1['Value'] = d1['Value'].str.replace('M','')
d1['Value'] = d1['Value'].str.replace('K','')
d1['Value'] = d1['Value'].str.replace('�','')
d1['Value'] = d1['Value'].apply(lambda x:x.strip())

In [163]:
d1['Value'].unique()

array(['110.5', '77', '118.5', '72', '102', '93', '67', '80', '51', '68',
       '76.5', '44', '60', '63', '89', '83.5', '78', '58', '53.5', '51.5',
       '38', '64.5', '27', '81', '69.5', '59.5', '62', '73.5', '59', '46',
       '43', '36', '57', '24', '30', '4', '64', '30.5', '62.5', '52',
       '45', '34', '46.5', '61', '41.5', '44.5', '56.5', '53', '50', '55',
       '36.5', '45.5', '43.5', '35', '39', '18', '21.5', '50.5', '54',
       '40.5', '37.5', '28.5', '37', '32', '26', '33', '38.5', '35.5',
       '9', '15.5', '22', '14', '42.5', '31.5', '42', '25', '29.5', '31',
       '24.5', '27.5', '29', '16.5', '23', '19', '4.2', '40', '41', '28',
       '22.5', '34.5', '32.5', '20', '26.5', '25.5', '21', '13', '17.5',
       '11.5', '8', '6', '19.5', '6.5', '20.5', '23.5', '18.5', '17',
       '12.5', '15', '13.5', '4.8', '3', '1.5', '16', '10', '11', '7',
       '14.5', '5.5', '10.5', '4.5', '12', '0', '9.5', '8.5', '2', '1.7',
       '1', '3.6', '7.5', '3.8', '5', '2.4', '2.9', '

In [164]:
d1['Wage'].unique()

array(['�565K', '�405K', '�290K', '�260K', '�355K', '�340K', '�420K',
       '�455K', '�380K', '�94K', '�205K', '�125K', '�285K', '�225K',
       '�145K', '�240K', '�315K', '�200K', '�130K', '�300K', '�215K',
       '�100K', '�255K', '�165K', '�265K', '�160K', '�150K', '�245K',
       '�110K', '�77K', '�115K', '�210K', '�195K', '�230K', '�250K',
       '�135K', '�155K', '�180K', '�175K', '�190K', '�185K', '�21K',
       '�82K', '�73K', '�92K', '�88K', '�96K', '�170K', '�66K', '�235K',
       '�28K', '�105K', '�38K', '�81K', '�57K', '�15K', '�63K', '�22K',
       '�84K', '�120K', '�90K', '�72K', '�93K', '�45K', '�74K', '�51K',
       '�42K', '�31K', '�75K', '�25K', '�140K', '�41K', '�78K', '�53K',
       '�95K', '�80K', '�43K', '�60K', '�85K', '�64K', '�67K', '�18K',
       '�70K', '�91K', '�20K', '�49K', '�87K', '�86K', '�26K', '�29K',
       '�55K', '�35K', '�33K', '�56K', '�30K', '�11K', '�59K', '�23K',
       '�46K', '�39K', '�32K', '�36K', '�98K', '�54K', '�68K', '�58K',
       '�2

In [165]:
d1['Wage'] = d1['Wage'].str.replace("�","")
d1['Wage'] = d1['Wage'].str.replace('K','')
d1['Wage'] = d1['Wage'].apply(lambda x:x.strip())

In [166]:
d1['Wage'].unique()

array(['565', '405', '290', '260', '355', '340', '420', '455', '380',
       '94', '205', '125', '285', '225', '145', '240', '315', '200',
       '130', '300', '215', '100', '255', '165', '265', '160', '150',
       '245', '110', '77', '115', '210', '195', '230', '250', '135',
       '155', '180', '175', '190', '185', '21', '82', '73', '92', '88',
       '96', '170', '66', '235', '28', '105', '38', '81', '57', '15',
       '63', '22', '84', '120', '90', '72', '93', '45', '74', '51', '42',
       '31', '75', '25', '140', '41', '78', '53', '95', '80', '43', '60',
       '85', '64', '67', '18', '70', '91', '20', '49', '87', '86', '26',
       '29', '55', '35', '33', '56', '30', '11', '59', '23', '46', '39',
       '32', '36', '98', '54', '68', '58', '27', '40', '44', '19', '1',
       '61', '50', '99', '17', '52', '62', '12', '10', '71', '14', '76',
       '48', '65', '69', '24', '34', '16', '37', '47', '89', '0', '97',
       '79', '13', '83', '6', '3', '9', '8', '7', '4', '2', '5'],
   

In [167]:
d1['Contract Valid Until'].unique()

array(['2021', '2022', '2020', '2023', '2019', '2024', '30-Jun-19',
       '2025', '2026', '31-Dec-18', '2018', nan, '31-May-20', '30-Jun-20',
       '31-May-19', '31-Dec-19', '01-Jan-19', '01-Jun-19', '04-Jan-19',
       '31-Jan-19', '07-Jan-19', '02-Jan-19', '06-Jan-19', '14-Oct-19',
       '03-Jan-19', '04-May-19', '12-Jan-19', '25-Jan-19', '18-Jan-19',
       '01-Dec-19', '30-Nov-18', '27-Feb-20', '05-Jan-19', '15-Jan-19',
       '30-Jan-19', '11-Jan-19', '20-Jan-19'], dtype=object)

In [168]:
d1.dropna(subset=['Contract Valid Until'],inplace=True)

In [169]:
from datetime import datetime
loc = []

for i in d1['Contract Valid Until']:
    if len(i)<=4:
        loc.append(int(i))
    else:
        a = datetime.strptime(i, '%d-%b-%y').year
        loc.append(a)

In [170]:
d1['Contract Valid Until'] = loc

In [225]:
d1['Contract Valid Until']

0        2021
1        2022
2        2022
3        2020
4        2023
         ... 
18202    2019
18203    2020
18204    2021
18205    2019
18206    2019
Name: Contract Valid Until, Length: 16643, dtype: int64

In [172]:
d1['Wage'] = pd.to_numeric(d1['Wage'])
d1['Value'] = pd.to_numeric(d1['Value'])

In [173]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17918 entries, 0 to 18206
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        17918 non-null  int64  
 1   Name                      17918 non-null  object 
 2   Age                       17918 non-null  int64  
 3   Nationality               17918 non-null  object 
 4   Overall                   17918 non-null  int64  
 5   Potential                 17918 non-null  int64  
 6   Club                      17918 non-null  object 
 7   Value                     17918 non-null  float64
 8   Wage                      17918 non-null  int64  
 9   Special                   17918 non-null  int64  
 10  Preferred Foot            17918 non-null  object 
 11  International Reputation  17918 non-null  float64
 12  Weak Foot                 17918 non-null  float64
 13  Skill Moves               17918 non-null  float64
 14  Work R

In [174]:
d1.shape

(17918, 24)

In [175]:
d1['ID'].unique()

array([158023,  20801, 190871, ..., 241638, 246268, 246269], dtype=int64)

In [176]:
d1['Name'].unique()

array(['L. Messi', 'Cristiano Ronaldo', 'Neymar Jr', ..., 'B. Worman',
       'D. Walker-Rice', 'G. Nugent'], dtype=object)

In [177]:
d1['Age'].unique()

array([31, 33, 26, 27, 32, 25, 29, 28, 24, 30, 19, 40, 22, 23, 34, 35, 36,
       37, 21, 18, 20, 39, 17, 38, 41, 45, 42, 16, 44], dtype=int64)

In [178]:
d1['Nationality'].unique()

array(['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium', 'Croatia',
       'Uruguay', 'Slovenia', 'Poland', 'Germany', 'France', 'England',
       'Italy', 'Egypt', 'Colombia', 'Denmark', 'Gabon', 'Wales',
       'Senegal', 'Costa Rica', 'Slovakia', 'Netherlands',
       'Bosnia Herzegovina', 'Morocco', 'Serbia', 'Algeria', 'Austria',
       'Greece', 'Chile', 'Sweden', 'Korea Republic', 'Finland', 'Guinea',
       'Montenegro', 'Armenia', 'Switzerland', 'Norway', 'Czech Republic',
       'Scotland', 'Ghana', 'Central African Rep.', 'DR Congo',
       'Ivory Coast', 'Russia', 'Ukraine', 'Iceland', 'Mexico', 'Jamaica',
       'Albania', 'Venezuela', 'Japan', 'Turkey', 'Ecuador', 'Paraguay',
       'Mali', 'Nigeria', 'Cameroon', 'Dominican Republic', 'Israel',
       'Kenya', 'Hungary', 'Republic of Ireland', 'Romania',
       'United States', 'Cape Verde', 'Australia', 'Peru', 'Togo',
       'Syria', 'Zimbabwe', 'Angola', 'Burkina Faso', 'Iran', 'Estonia',
       'Tunisia', 'Equato

In [179]:
d1['Overall'].unique()

array([94, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46],
      dtype=int64)

In [180]:
d1['Potential'].unique()

array([94, 93, 92, 91, 90, 89, 95, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79,
       78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62,
       61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 48], dtype=int64)

In [181]:
d1['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Paris Saint-Germain',
       'Manchester United', 'Manchester City', 'Chelsea', 'Real Madrid',
       'Atl�tico Madrid', 'FC Bayern M�nchen', 'Tottenham Hotspur',
       'Liverpool', 'Napoli', 'Arsenal', 'Milan', 'Inter', 'Lazio',
       'Borussia Dortmund', 'Vissel Kobe', 'Olympique Lyonnais', 'Roma',
       'Valencia CF', 'Guangzhou Evergrande Taobao FC', 'FC Porto',
       'FC Schalke 04', 'Be?ikta? JK', 'LA Galaxy', 'Sporting CP',
       'Real Betis', 'Olympique de Marseille', 'RC Celta',
       'Bayer 04 Leverkusen', 'Real Sociedad', 'Villarreal CF',
       'Sevilla FC', 'SL Benfica', 'AS Saint-�tienne', 'AS Monaco',
       'Leicester City', 'Atalanta', 'Gr�mio', 'Atl�tico Mineiro',
       'RB Leipzig', 'Ajax', 'Dalian YiFang FC', 'Everton',
       'West Ham United', '1. FC K�ln', 'TSG 1899 Hoffenheim',
       'Shanghai SIPG FC', 'OGC Nice', 'Al Nassr',
       'Wolverhampton Wanderers', 'Borussia M�nchengladbach',
       'Hertha BSC', 'SV Werder

In [182]:
d1['Special'].unique()

array([2202, 2228, 2143, ...,  778,  738,  731], dtype=int64)

In [183]:
d1['Preferred Foot'].unique()

array(['Left', 'Right'], dtype=object)

In [184]:
d1['International Reputation']

0        5.0
1        5.0
2        5.0
3        4.0
4        4.0
        ... 
18202    1.0
18203    1.0
18204    1.0
18205    1.0
18206    1.0
Name: International Reputation, Length: 17918, dtype: float64

In [185]:
d1['Weak Foot']

0        4.0
1        4.0
2        5.0
3        3.0
4        5.0
        ... 
18202    2.0
18203    2.0
18204    3.0
18205    3.0
18206    3.0
Name: Weak Foot, Length: 17918, dtype: float64

In [186]:
d1['Skill Moves']

0        4.0
1        5.0
2        5.0
3        1.0
4        4.0
        ... 
18202    2.0
18203    2.0
18204    2.0
18205    2.0
18206    2.0
Name: Skill Moves, Length: 17918, dtype: float64

In [187]:
d1['Work Rate'].unique()

array(['Medium/ Medium', 'High/ Low', 'High/ Medium', 'High/ High',
       'Medium/ High', 'Medium/ Low', 'Low/ High', 'Low/ Medium',
       'Low/ Low'], dtype=object)

In [188]:
d1['Body Type'].unique()

array(['Messi', 'C. Ronaldo', 'Neymar', 'Lean', 'Normal', 'Courtois',
       'Stocky', 'PLAYER_BODY_TYPE_25', 'Shaqiri', 'Akinfenwa'],
      dtype=object)

In [189]:
d1['Real Face'].unique()

array(['Yes', 'No'], dtype=object)

In [190]:
d1['Position'].unique()

array(['RF', 'ST', 'LW', 'GK', 'RCM', 'LF', 'RS', 'RCB', 'LCM', 'CB',
       'LDM', 'CAM', 'CDM', 'LS', 'LCB', 'RM', 'LAM', 'LM', 'LB', 'RDM',
       'RW', 'CM', 'RB', 'RAM', 'CF', 'RWB', 'LWB'], dtype=object)

In [191]:
d1['Jersey Number'].unique()

array([10.,  7.,  1.,  9., 15.,  8., 21., 13., 22.,  5.,  3., 14., 12.,
       11.,  2., 23., 26.,  6., 17., 18.,  4., 19., 31., 25., 37., 30.,
       44., 29., 24., 20., 16., 33., 28., 27., 77., 47., 38., 40., 92.,
       36., 87., 34., 32., 83., 70., 35., 89., 56., 99., 57., 91., 86.,
       45., 63., 39., 43., 42., 93., 72., 71., 88., 55., 80., 50., 66.,
       60., 73., 67., 74., 69., 76., 41., 90., 46., 75., 79., 62., 81.,
       61., 49., 95., 53., 96., 97., 68., 98., 94., 58., 78., 48., 52.,
       54., 84., 82., 65., 64., 51., 59., 85.])

In [192]:
d1['Joined'].unique()

array(['01-Jul-04', '10-Jul-18', '03-Aug-17', ..., '22-May-17',
       '06-Nov-16', '27-Nov-18'], dtype=object)

In [193]:
d1['Joined'].isnull().sum()/len(d1)*100

7.0543587453956915

In [194]:
d1.dropna(subset=['Joined'],inplace=True)

In [195]:
d1['Joined'] = pd.to_datetime(d1['Joined']).dt.year

In [196]:
d1['Joined']

0        2004
1        2018
2        2017
3        2011
4        2015
         ... 
18202    2017
18203    2018
18204    2017
18205    2018
18206    2018
Name: Joined, Length: 16654, dtype: int64

In [197]:
d1['Height'].unique()

array(["5'7", "6'2", "5'9", "6'4", "5'11", "5'8", "6'0", "5'6", "5'10",
       "6'6", "6'1", "5'4", "6'3", "5'5", "6'5", "6'7", "5'3", "5'2",
       "6'8", "5'1", "6'9"], dtype=object)

In [198]:
d1.dropna(subset=['Height'],inplace=True)

In [199]:
d1['Height'] = d1['Height'].apply(lambda x:x.replace("'",'.'))

In [200]:
d1['Height'] = d1['Height'].astype(float)

In [201]:
d1['Height']

0        5.70
1        6.20
2        5.90
3        6.40
4        5.11
         ... 
18202    5.90
18203    6.30
18204    5.80
18205    5.10
18206    5.10
Name: Height, Length: 16654, dtype: float64

In [202]:
d1['Weight'].unique()

array(['159lbs', '183lbs', '150lbs', '168lbs', '154lbs', '163lbs',
       '146lbs', '190lbs', '181lbs', '192lbs', '176lbs', '172lbs',
       '148lbs', '165lbs', '196lbs', '161lbs', '187lbs', '212lbs',
       '170lbs', '203lbs', '157lbs', '185lbs', '130lbs', '174lbs',
       '207lbs', '134lbs', '141lbs', '152lbs', '179lbs', '132lbs',
       '201lbs', '198lbs', '209lbs', '214lbs', '143lbs', '205lbs',
       '137lbs', '194lbs', '216lbs', '139lbs', '220lbs', '126lbs',
       '218lbs', '123lbs', '128lbs', '223lbs', '121lbs', '115lbs',
       '117lbs', '236lbs', '229lbs', '243lbs', '225lbs', '227lbs',
       '110lbs', '119lbs', '234lbs'], dtype=object)

In [203]:
d1['Weight'] = d1['Weight'].apply(lambda x:x.replace('lbs',''))

In [204]:
d1['Weight'] = d1['Weight'].astype(int)

In [205]:
d1['Weight']

0        159
1        183
2        150
3        168
4        154
        ... 
18202    134
18203    170
18204    148
18205    154
18206    176
Name: Weight, Length: 16654, dtype: int32

In [206]:
d1['Release Clause'].unique()

array(['�226.5M', '�127.1M', '�228.1M', ..., '�74K', '�101K', '�147K'],
      dtype=object)

In [207]:
d1['Release Clause'].isnull().sum()/len(d1)*100

0.06605019815059446

In [208]:
d1.dropna(subset=['Release Clause'],inplace=True)

In [209]:
d1['Release Clause'] = d1['Release Clause'].apply(lambda x:x.replace('M',''))
d1['Release Clause'] = d1['Release Clause'].apply(lambda x:x.replace('�',''))
d1['Release Clause'] = d1['Release Clause'].apply(lambda x:x.replace('K',''))
d1['Release Clause'] = d1['Release Clause'].apply(lambda x:x.strip())

In [210]:
d1['Release Clause'] = d1['Release Clause'].astype(float)

In [211]:
d1['Release Clause']

0        226.5
1        127.1
2        228.1
3        138.6
4        196.4
         ...  
18202    143.0
18203    113.0
18204    165.0
18205    143.0
18206    165.0
Name: Release Clause, Length: 16643, dtype: float64

In [212]:
d1.drop(['Real Face','Jersey Number'],axis=1,inplace=True)

In [213]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16643 entries, 0 to 18206
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        16643 non-null  int64  
 1   Name                      16643 non-null  object 
 2   Age                       16643 non-null  int64  
 3   Nationality               16643 non-null  object 
 4   Overall                   16643 non-null  int64  
 5   Potential                 16643 non-null  int64  
 6   Club                      16643 non-null  object 
 7   Value                     16643 non-null  float64
 8   Wage                      16643 non-null  int64  
 9   Special                   16643 non-null  int64  
 10  Preferred Foot            16643 non-null  object 
 11  International Reputation  16643 non-null  float64
 12  Weak Foot                 16643 non-null  float64
 13  Skill Moves               16643 non-null  float64
 14  Work R

In [214]:
d1_num = d1.select_dtypes(np.number)
d1_num.head()

ID  Age  Overall  Potential  Value  Wage  Special  \
0  158023   31       94         94  110.5   565     2202   
1   20801   33       94         94   77.0   405     2228   
2  190871   26       92         93  118.5   290     2143   
3  193080   27       91         93   72.0   260     1471   
4  192985   27       91         92  102.0   355     2281   

   International Reputation  Weak Foot  Skill Moves  Joined  \
0                       5.0        4.0          4.0    2004   
1                       5.0        4.0          5.0    2018   
2                       5.0        5.0          5.0    2017   
3                       4.0        3.0          1.0    2011   
4                       4.0        5.0          4.0    2015   

   Contract Valid Until  Height  Weight  Release Clause  
0                  2021    5.70     159           226.5  
1                  2022    6.20     183           127.1  
2                  2022    5.90     150           228.1  
3                  2020    6.40     168           138.6  
4                  2023    5.11     154           196.4

In [215]:
d1_cat = d1.select_dtypes(object)
d1_cat.head()

Name Nationality                 Club Preferred Foot  \
0           L. Messi   Argentina         FC Barcelona           Left   
1  Cristiano Ronaldo    Portugal             Juventus          Right   
2          Neymar Jr      Brazil  Paris Saint-Germain          Right   
3             De Gea       Spain    Manchester United          Right   
4       K. De Bruyne     Belgium      Manchester City          Right   

        Work Rate   Body Type Position  
0  Medium/ Medium       Messi       RF  
1       High/ Low  C. Ronaldo       ST  
2    High/ Medium      Neymar       LW  
3  Medium/ Medium        Lean       GK  
4      High/ High      Normal      RCM

In [216]:
d1_num.isnull().sum()

ID                          0
Age                         0
Overall                     0
Potential                   0
Value                       0
Wage                        0
Special                     0
International Reputation    0
Weak Foot                   0
Skill Moves                 0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [217]:
d1_num.shape

(16643, 15)

In [218]:
d1_cat.isnull().sum()

Name              0
Nationality       0
Club              0
Preferred Foot    0
Work Rate         0
Body Type         0
Position          0
dtype: int64

In [219]:
d1_cat.shape

(16643, 7)

In [221]:
d2 = pd.concat([d1_num,d1_cat],axis=1)
d2.head()

ID  Age  Overall  Potential  Value  Wage  Special  \
0  158023   31       94         94  110.5   565     2202   
1   20801   33       94         94   77.0   405     2228   
2  190871   26       92         93  118.5   290     2143   
3  193080   27       91         93   72.0   260     1471   
4  192985   27       91         92  102.0   355     2281   

   International Reputation  Weak Foot  Skill Moves  ...  Height  Weight  \
0                       5.0        4.0          4.0  ...    5.70     159   
1                       5.0        4.0          5.0  ...    6.20     183   
2                       5.0        5.0          5.0  ...    5.90     150   
3                       4.0        3.0          1.0  ...    6.40     168   
4                       4.0        5.0          4.0  ...    5.11     154   

   Release Clause               Name  Nationality                 Club  \
0           226.5           L. Messi    Argentina         FC Barcelona   
1           127.1  Cristiano Ronaldo     Portugal             Juventus   
2           228.1          Neymar Jr       Brazil  Paris Saint-Germain   
3           138.6             De Gea        Spain    Manchester United   
4           196.4       K. De Bruyne      Belgium      Manchester City   

  Preferred Foot       Work Rate   Body Type Position  
0           Left  Medium/ Medium       Messi       RF  
1          Right       High/ Low  C. Ronaldo       ST  
2          Right    High/ Medium      Neymar       LW  
3          Right  Medium/ Medium        Lean       GK  
4          Right      High/ High      Normal      RCM  

[5 rows x 22 columns]

In [222]:
d2.isnull().sum().sum()

0

In [223]:
d2.shape

(16643, 22)

In [ ]:
import pandas as pd

In [224]:
d2.to_excel('football_players_T.xlsx')